/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class NyatDbNative {
  static open(opts: OpenOptions): NyatDbNative
  path(): string
  stats(): EngineStatsJs
  checkpoint(): void
  verify(): number
  chatAppend(chatId: number, msg: ChatAppendInput): void
  chatRecent(chatId: number, limit?: number | undefined | null): Array<ChatMessageJs>
  chatGet(chatId: number, messageId: number): ChatMessageJs | null
  /** Parallel decode batch (rayon). Returns one entry per id (null if missing). */
  chatGetBatch(chatId: number, messageIds: Array<number>): Array<ChatMessageJs | undefined | null>
  chatTrimKeepLast(chatId: number, keep: number): void
  hotSet(key: string, value: Buffer, ttlMs?: number | undefined | null): void
  hotGet(key: string): Buffer | null
  hotGetString(key: string): string | null
  hotDel(key: string): void
  impulseSchedule(id: string, chatId: number, runAt: number, kind: string, payload: Buffer): void
  impulseDue(now?: number | undefined | null, limit?: number | undefined | null): Array<ImpulseJs>
  impulseAck(id: string): void
  bondUpsert(b: BondJs): void
  bondList(limit?: number | undefined | null): Array<BondJs>
  recallUpsert(chatId: number, messageId: number, vector: Float64Array, visibility?: number | undefined | null): void
  recallSearch(query: Float64Array, chatId?: number | undefined | null, topK?: number | undefined | null): Array<RecallHitJs>
  close(skipCheckpoint?: boolean | undefined | null): void
  ping(): string
}

export interface BondJs {
  uid: number
  chatId: number
  score: number
  note: string
}

export interface ChatAppendInput {
  messageId: number
  ts: number
  uid: number
  /** "user" | "assistant" | "system" */
  role: string
  text: string
  /** "text" | "json" — default text */
  bodyFormat?: string
}

export interface ChatMessageJs {
  messageId: number
  ts: number
  uid: number
  role: number
  roleName: string
  text: string
  /** "text" | "json" */
  bodyFormat: string
}

export interface EngineStatsJs {
  pages: number
  chats: number
  recalls: number
  indexed: number
  lsn: string
  backend: string
  schema: number
  poolCached: number
  poolDirty: number
}

export interface ImpulseJs {
  id: string
  chatId: number
  runAt: number
  kind: string
  payload: Array<number>
}

export declare function nativeVersion(): string

export interface OpenOptions {
  path: string
  syncEvery?: number
  poolFrames?: number
  chatRingMax?: number
  verifyOnOpen?: boolean
}

export interface RecallHitJs {
  chatId: number
  messageId: number
  score: number
}

export declare function schemaVersion(): number
